#!/bin/bash

LOGIN_PROFILE_PATH=(
	"/etc/profile"
	"$HOME/.bash_profile"
	"$HOME/.bash_login"
	"$HOME/.profile"
	"$HOME/.bashrc"
)

echo "Login scripts:"

INDEX=0
for PROFILE in ${LOGIN_PROFILE_PATH[@]};
do
	if [[ -e $PROFILE ]];
	then
		echo "[$INDEX] $PROFILE";
		INDEX=$(expr $INDEX + 1)
	fi
done
